### PR TITLE
[data] Adding chrisostrouchov.com blog.

### PR DESCRIPTION
**Pull request by costrouc**
### All Submissions:

* [X] Have you followed the guidelines in our [Contributing](https://github.com/KnoxDevs/knoxdevs.github.io/blob/master/Contributing.md) document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/KnoxDevs/knoxdevs.github.io/pulls) for the same update/change?

### Data Submissions:

1. [X] Does your submission pass tests?
    - [X] valid `yaml`
    - [X] follows template for the data type submitting.
2. [X] Have you lint your code locally prior to submission?

### New Feature Submissions:

1. [X] Does your submission pass tests?
2. [X] Have you lint your code locally prior to submission?

This pull request does two things.
  - adds my blog to the knoxdevs site.
  - updates the blogger template to use `blurb` instead of `content`

### CODE REVIEW

**Comment by costrouc** [comment]
Oh and I will also add that I corrected a relative link that was used in "Adam Byram's" blog post.

**Review by alexpawlowski — CHANGES_REQUESTED** [review]
Everything looks good. I changed the format on you after you submitted, because my computer died, so this request changes is my bad.

From @wigging 's comments #2 , I decided to change the `yml` format to:
- have spaces between each key to improve readability
- blurb was too informal, so have changed that to description
- have separated `online` into `online` and `social`. 

If you can change that, this will be good to go!

**Comment by costrouc** [comment]
I have update the `_pages/blogger.md` template to include `github` link and use description in yaml spec instead of blurb.

Additionally I have modified adam byram's yml to follow the spec correctly. 

Two images have been added (of myself and adam byram)

**Review by alexpawlowski — APPROVED** [review]
Looks great! Thanks for doing this!

**Pull request merged**
